name: Build App-2
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  trigger-reusable-workflow:
    uses: DolVladzio/release-rollback-repo/.github/workflows/build-images.yaml@main
    with:
      version: ${{ github.ref_name }}
      app-name: ${{ github.event.repository.name }}